# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p:\API\GUI\ui\Facebook\Checker.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(596, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Email_Password = QtWidgets.QRadioButton(self.widget)
        self.Email_Password.setObjectName("Email_Password")
        self.horizontalLayout.addWidget(self.Email_Password)
        self.Cookie = QtWidgets.QRadioButton(self.widget)
        self.Cookie.setObjectName("Cookie")
        self.horizontalLayout.addWidget(self.Cookie)
        self.verticalLayout.addWidget(self.widget)
        self.widget_Info = QtWidgets.QWidget(Form)
        self.widget_Info.setObjectName("widget_Info")
        self.verticalLayout.addWidget(self.widget_Info)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Start = QtWidgets.QPushButton(self.widget_2)
        self.Start.setObjectName("Start")
        self.horizontalLayout_8.addWidget(self.Start)
        self.Cancel = QtWidgets.QPushButton(self.widget_2)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_8.addWidget(self.Cancel)
        self.verticalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Email_Password.setText(_translate("Form", "Email w Password"))
        self.Cookie.setText(_translate("Form", "Cookies"))
        self.Start.setText(_translate("Form", "Start"))
        self.Cancel.setText(_translate("Form", "Cancel"))
