# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p:\API\GUI\ui\Facebook\Manger_face.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1182, 349)
        Form.setStyleSheet("QPushButton l{\n"
"        border:none;\n"
"        border-radius: 3px;\n"
"        text-align: left;\n"
"        padding: 8px 0 8px 15px;\n"
"        color: #788596;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"\n"
"    QPushButton:checked {\n"
"        color: #fff;\n"
"    }\n"
"QScrollArea{\n"
"border: none;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(5)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.widget_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.Select_all = QtWidgets.QPushButton(self.widget_3)
        self.Select_all.setObjectName("Select_all")
        self.horizontalLayout.addWidget(self.Select_all)
        self.widget_select = QtWidgets.QWidget(self.widget_3)
        self.widget_select.setObjectName("widget_select")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_select)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_select)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_select)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.Select = QtWidgets.QPushButton(self.widget_select)
        self.Select.setObjectName("Select")
        self.horizontalLayout_4.addWidget(self.Select)
        self.horizontalLayout.addWidget(self.widget_select)
        self.Refresh = QtWidgets.QPushButton(self.widget_3)
        self.Refresh.setObjectName("Refresh")
        self.horizontalLayout.addWidget(self.Refresh)
        self.horizontalLayout_3.addWidget(self.widget_3, 0, QtCore.Qt.AlignLeft)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Epsilon = QtWidgets.QPushButton(self.widget_4)
        self.Epsilon.setMinimumSize(QtCore.QSize(0, 0))
        self.Epsilon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Epsilon.setStyleSheet("QPushButton:checked{\n"
"background-color: rgb(255, 0, 0);\n"
"}")
        self.Epsilon.setCheckable(True)
        self.Epsilon.setObjectName("Epsilon")
        self.horizontalLayout_2.addWidget(self.Epsilon)
        self.Change = QtWidgets.QPushButton(self.widget_4)
        self.Change.setMinimumSize(QtCore.QSize(0, 0))
        self.Change.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Change.setStyleSheet("QPushButton:checked{\n"
"background-color: rgb(255, 0, 0);\n"
"}")
        self.Change.setCheckable(True)
        self.Change.setObjectName("Change")
        self.horizontalLayout_2.addWidget(self.Change)
        self.Check = QtWidgets.QPushButton(self.widget_4)
        self.Check.setCheckable(True)
        self.Check.setObjectName("Check")
        self.horizontalLayout_2.addWidget(self.Check)
        self.Update = QtWidgets.QPushButton(self.widget_4)
        self.Update.setMinimumSize(QtCore.QSize(0, 0))
        self.Update.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Update.setStyleSheet("QPushButton:checked{\n"
"background-color: rgb(255, 0, 0);\n"
"}")
        self.Update.setCheckable(True)
        self.Update.setObjectName("Update")
        self.horizontalLayout_2.addWidget(self.Update)
        self.Login = QtWidgets.QPushButton(self.widget_4)
        self.Login.setMinimumSize(QtCore.QSize(0, 0))
        self.Login.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Login.setStyleSheet("QPushButton:checked{\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"")
        self.Login.setCheckable(True)
        self.Login.setChecked(False)
        self.Login.setObjectName("Login")
        self.horizontalLayout_2.addWidget(self.Login)
        self.Delete_all = QtWidgets.QPushButton(self.widget_4)
        self.Delete_all.setMinimumSize(QtCore.QSize(0, 0))
        self.Delete_all.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Delete_all.setStyleSheet("QPushButton:checked{\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"")
        self.Delete_all.setCheckable(True)
        self.Delete_all.setObjectName("Delete_all")
        self.horizontalLayout_2.addWidget(self.Delete_all)
        self.Write_Change = QtWidgets.QPushButton(self.widget_4)
        self.Write_Change.setEnabled(False)
        self.Write_Change.setObjectName("Write_Change")
        self.horizontalLayout_2.addWidget(self.Write_Change)
        self.AddMultiAccount = QtWidgets.QPushButton(self.widget_4)
        self.AddMultiAccount.setMinimumSize(QtCore.QSize(0, 0))
        self.AddMultiAccount.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.AddMultiAccount.setObjectName("AddMultiAccount")
        self.horizontalLayout_2.addWidget(self.AddMultiAccount)
        self.Export = QtWidgets.QPushButton(self.widget_4)
        self.Export.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Export.setObjectName("Export")
        self.horizontalLayout_2.addWidget(self.Export)
        self.horizontalLayout_3.addWidget(self.widget_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.widget_2)
        self.table = QtWidgets.QTableWidget(self.widget)
        self.table.setStyleSheet("")
        self.table.setObjectName("table")
        self.table.setColumnCount(7)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        self.table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table)
        self.widget_save = QtWidgets.QWidget(self.widget)
        self.widget_save.setObjectName("widget_save")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_save)
        self.gridLayout_2.setContentsMargins(0, 5, 0, 5)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Save = QtWidgets.QPushButton(self.widget_save)
        self.Save.setObjectName("Save")
        self.gridLayout_2.addWidget(self.Save, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.widget_save)
        self.widget_Info = QtWidgets.QWidget(self.splitter)
        self.widget_Info.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_Info.setObjectName("widget_Info")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Searsh"))
        self.comboBox.setItemText(0, _translate("Form", "Group"))
        self.comboBox.setItemText(1, _translate("Form", "Name"))
        self.comboBox.setItemText(2, _translate("Form", "email"))
        self.comboBox.setItemText(3, _translate("Form", "password"))
        self.comboBox.setItemText(4, _translate("Form", "Usename"))
        self.comboBox.setItemText(5, _translate("Form", "Cookies"))
        self.Select_all.setText(_translate("Form", "Select All"))
        self.label.setText(_translate("Form", "OR"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Number Accounts"))
        self.Select.setText(_translate("Form", "Select"))
        self.Refresh.setText(_translate("Form", "Refresh"))
        self.Epsilon.setText(_translate("Form", "Epsilon"))
        self.Change.setText(_translate("Form", "Change Email"))
        self.Check.setText(_translate("Form", "Check"))
        self.Update.setText(_translate("Form", "Update"))
        self.Login.setText(_translate("Form", "Login"))
        self.Delete_all.setText(_translate("Form", "Delete"))
        self.Write_Change.setText(_translate("Form", "Write Change"))
        self.AddMultiAccount.setToolTip(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Format:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Group</span>:<span style=\" font-weight:600;\">Name</span>:<span style=\" font-weight:600;\">Email</span>:<span style=\" font-weight:600;\">Password</span>:<span style=\" font-weight:600;\">UserName</span>:<span style=\" font-weight:600;\">Cookies</span>:<span style=\" font-weight:600;\">Type:Insta</span></p></body></html>"))
        self.AddMultiAccount.setText(_translate("Form", "Add Account"))
        self.Export.setText(_translate("Form", "Export"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "New Column"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "New Column"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "New Column"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "New Column"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "New Column"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "New Column"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "New Column"))
        self.Save.setText(_translate("Form", "Save"))
