# Form implementation generated from reading ui file 'p:\API\GUI\ui\Insta\Manger_insta.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1008, 476)
        Form.setStyleSheet("QPushButton l{\n"
"        border:none;\n"
"        border-radius: 3px;\n"
"        text-align: left;\n"
"        padding: 8px 0 8px 15px;\n"
"        color: #788596;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"\n"
"    QPushButton:checked {\n"
"        color: #fff;\n"
"    }\n"
"QScrollArea{\n"
"border: none;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_3)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(parent=self.widget_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout_3.addWidget(self.widget_3, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Add_Account = QtWidgets.QPushButton(parent=self.widget_4)
        self.Add_Account.setObjectName("Add_Account")
        self.horizontalLayout_2.addWidget(self.Add_Account)
        self.AddMultiAccount = QtWidgets.QPushButton(parent=self.widget_4)
        self.AddMultiAccount.setObjectName("AddMultiAccount")
        self.horizontalLayout_2.addWidget(self.AddMultiAccount)
        self.Export = QtWidgets.QPushButton(parent=self.widget_4)
        self.Export.setObjectName("Export")
        self.horizontalLayout_2.addWidget(self.Export)
        self.horizontalLayout_3.addWidget(self.widget_4, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Searsh"))
        self.comboBox.setItemText(0, _translate("Form", "Group"))
        self.comboBox.setItemText(1, _translate("Form", "Username"))
        self.comboBox.setItemText(2, _translate("Form", "Email"))
        self.comboBox.setItemText(3, _translate("Form", "Password"))
        self.comboBox.setItemText(4, _translate("Form", "Cookies"))
        self.comboBox.setItemText(5, _translate("Form", "Type"))
        self.pushButton.setText(_translate("Form", "Searsh"))
        self.Add_Account.setText(_translate("Form", "AddAcount"))
        self.AddMultiAccount.setToolTip(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Format:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Group</span>:<span style=\" font-weight:600;\">UserName</span>:<span style=\" font-weight:600;\">Email</span>:<span style=\" font-weight:600;\">Password</span>:<span style=\" font-weight:600;\">Cookies</span>:<span style=\" font-weight:600;\">Type</span></p></body></html>"))
        self.AddMultiAccount.setText(_translate("Form", "Add Multi Account"))
        self.Export.setText(_translate("Form", "Export"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "New Column"))
