# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p:\API\GUI\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1149, 627)
        MainWindow.setStyleSheet("#icon_only_widget {\n"
"        background-color: #313a46;\n"
"        width:50px;\n"
"    }\n"
"#full_menu_widget,#widget_tab {\n"
"        background-color: #313a46;\n"
"    }\n"
"#full_menu_widget QPushButton,#label_2,#label_4 {\n"
"        border:none;\n"
"        text-align: left;\n"
"        color: #ffffff;\n"
"    }\n"
"#full_menu_widget QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"\n"
"    #full_menu_widget QPushButton:checked {\n"
"        color: #fff;\n"
"    }\n"
"#logo_label_2 {\n"
"        color: #fff;\n"
"    }\n"
"#change_btn {\n"
"        padding: 5px;\n"
"        border: none;\n"
"        width: 30px;\n"
"        height: 30px;\n"
"    }\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_tab = QtWidgets.QWidget(self.centralwidget)
        self.widget_tab.setObjectName("widget_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_tab)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icon/icon/logo.ico"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget_tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(975, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Minimize = QtWidgets.QPushButton(self.widget_tab)
        self.Minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Minimize.setIcon(icon)
        self.Minimize.setFlat(True)
        self.Minimize.setObjectName("Minimize")
        self.horizontalLayout_2.addWidget(self.Minimize)
        self.Maximize = QtWidgets.QPushButton(self.widget_tab)
        self.Maximize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/Maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Maximize.setIcon(icon1)
        self.Maximize.setFlat(True)
        self.Maximize.setObjectName("Maximize")
        self.horizontalLayout_2.addWidget(self.Maximize)
        self.Close = QtWidgets.QPushButton(self.widget_tab)
        self.Close.setStyleSheet("QPushButton:hover {\n"
"    color: rgb(255, 26, 26);\n"
"}")
        self.Close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close.setIcon(icon2)
        self.Close.setFlat(True)
        self.Close.setObjectName("Close")
        self.horizontalLayout_2.addWidget(self.Close)
        self.verticalLayout.addWidget(self.widget_tab)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(self.widget_7)
        self.icon_only_widget.setMaximumSize(QtCore.QSize(30, 16777215))
        self.icon_only_widget.setStyleSheet("")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(5, 0, 0, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.icon_only_widget)
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("p:\\API\\GUI\\ui\\../static/icon/menu.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setCheckable(True)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.logo_label = QtWidgets.QLabel(self.icon_only_widget)
        self.logo_label.setMaximumSize(QtCore.QSize(20, 20))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("p:\\API\\GUI\\ui\\../static/icon/facebook.ico"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_3.addWidget(self.logo_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 381, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.icon_only_widget)
        self.label.setMaximumSize(QtCore.QSize(16, 16))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/icon/people.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_7)
        self.scrollArea.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(120, 16777215))
        self.scrollArea.setStyleSheet("border: none;\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.full_menu_widget = QtWidgets.QWidget()
        self.full_menu_widget.setGeometry(QtCore.QRect(0, 0, 120, 585))
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.full_menu_widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_9 = QtWidgets.QWidget(self.full_menu_widget)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_6.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/arrow-3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/arrow-4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setChecked(False)
        self.pushButton_6.setAutoExclusive(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.gridLayout_2.addWidget(self.widget_9, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.full_menu_widget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 5, 0, 1, 1)
        self.mac = QtWidgets.QPushButton(self.full_menu_widget)
        self.mac.setText("")
        self.mac.setObjectName("mac")
        self.gridLayout_2.addWidget(self.mac, 6, 0, 1, 1)
        self.menu_facebook = QtWidgets.QWidget(self.full_menu_widget)
        self.menu_facebook.setObjectName("menu_facebook")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.menu_facebook)
        self.verticalLayout_6.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Account_Manger_face = QtWidgets.QPushButton(self.menu_facebook)
        self.Account_Manger_face.setObjectName("Account_Manger_face")
        self.verticalLayout_6.addWidget(self.Account_Manger_face)
        self.Account_Edit_face = QtWidgets.QPushButton(self.menu_facebook)
        self.Account_Edit_face.setObjectName("Account_Edit_face")
        self.verticalLayout_6.addWidget(self.Account_Edit_face)
        self.Account_Generat_face = QtWidgets.QPushButton(self.menu_facebook)
        self.Account_Generat_face.setObjectName("Account_Generat_face")
        self.verticalLayout_6.addWidget(self.Account_Generat_face)
        self.User = QtWidgets.QPushButton(self.menu_facebook)
        self.User.setObjectName("User")
        self.verticalLayout_6.addWidget(self.User)
        self.Post = QtWidgets.QPushButton(self.menu_facebook)
        self.Post.setObjectName("Post")
        self.verticalLayout_6.addWidget(self.Post)
        self.Follow_face = QtWidgets.QPushButton(self.menu_facebook)
        self.Follow_face.setObjectName("Follow_face")
        self.verticalLayout_6.addWidget(self.Follow_face)
        self.Like_face = QtWidgets.QPushButton(self.menu_facebook)
        self.Like_face.setObjectName("Like_face")
        self.verticalLayout_6.addWidget(self.Like_face)
        self.Share_face = QtWidgets.QPushButton(self.menu_facebook)
        self.Share_face.setObjectName("Share_face")
        self.verticalLayout_6.addWidget(self.Share_face)
        self.Report_face = QtWidgets.QPushButton(self.menu_facebook)
        self.Report_face.setObjectName("Report_face")
        self.verticalLayout_6.addWidget(self.Report_face)
        self.gridLayout_2.addWidget(self.menu_facebook, 4, 0, 1, 1)
        self.scrollArea.setWidget(self.full_menu_widget)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_7, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.tabWidget = QtWidgets.QTabWidget(self.widget_6)
        self.tabWidget.setStyleSheet("#tabWidget {\n"
"    background-color: rgb(255, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"    margin-left: 3px;\n"
"    image:  url(:/icon/icon/x-mark-1.ico)\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    \n"
"    image: url(:/icon/icon/x-mark-2.ico)\n"
"}\n"
"QTabBar::tab  {\n"
"                background: white;\n"
"                background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f6f6f6, stop:1 #e0e0e0);\n"
"                border: solid #0066cc 2px;\n"
"                border-radius: 50px 50px 50px 50px;\n"
"                padding: 8px 16px;\n"
"                margin-right: 4px;\n"
"\n"
"                \n"
"}\n"
"QTabBar::tab:selected {\n"
"                background: white;\n"
"                border-color: #ccc;\n"
"                border-radius: 33px 34px 0px 0px;\n"
"border: solid #0066cc 2px;\n"
"            }")
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        self.pushButton.toggled['bool'].connect(self.scrollArea.setVisible) # type: ignore
        self.pushButton_6.toggled['bool'].connect(self.menu_facebook.setVisible) # type: ignore
        self.Minimize.clicked.connect(MainWindow.showMinimized) # type: ignore
        self.Close.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "SMM"))
        self.pushButton_6.setText(_translate("MainWindow", "FACEBOOK"))
        self.Account_Manger_face.setText(_translate("MainWindow", "Account Manager"))
        self.Account_Edit_face.setText(_translate("MainWindow", "Account Edit"))
        self.Account_Generat_face.setText(_translate("MainWindow", "Account Generat"))
        self.User.setText(_translate("MainWindow", "User"))
        self.Post.setText(_translate("MainWindow", "Post"))
        self.Follow_face.setText(_translate("MainWindow", "Follow"))
        self.Like_face.setText(_translate("MainWindow", "Like"))
        self.Share_face.setText(_translate("MainWindow", "Share"))
        self.Report_face.setText(_translate("MainWindow", "Report"))
import resource_rc
