# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/kareem/AppData/Local/Temp/GeneratUnoMgS.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(870, 818)
        Form.setStyleSheet("\n"
"QPushButton l{\n"
"        border:none;\n"
"        border-radius: 3px;\n"
"        text-align: left;\n"
"        padding: 8px 0 8px 15px;\n"
"        color: #788596;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"\n"
"    QPushButton:checked {\n"
"        color: #fff;\n"
"    }\n"
"QScrollArea{\n"
"border: none;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 870, 818))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_Name = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_Name.setObjectName("widget_Name")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_Name)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_Name)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.widget_Name)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.checkBox = QtWidgets.QCheckBox(self.widget_Name)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.gridLayout_2.addWidget(self.widget_Name, 1, 0, 1, 1)
        self.widget_Password = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_Password.setObjectName("widget_Password")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_Password)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget_Password)
        self.lineEdit_password.setText("")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_5.addWidget(self.lineEdit_password)
        self.label_5 = QtWidgets.QLabel(self.widget_Password)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.checkBox_password = QtWidgets.QCheckBox(self.widget_Password)
        self.checkBox_password.setObjectName("checkBox_password")
        self.horizontalLayout_5.addWidget(self.checkBox_password)
        self.gridLayout_2.addWidget(self.widget_Password, 5, 0, 1, 1)
        self.widget_Name1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_Name1.setObjectName("widget_Name1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_Name1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_Name1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.radioButton = QtWidgets.QRadioButton(self.widget_Name1)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_Name1)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_Name1)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.gridLayout_2.addWidget(self.widget_Name1, 2, 0, 1, 1)
        self.widget_Email1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_Email1.setObjectName("widget_Email1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_Email1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget_Email1)
        self.radioButton_4.setEnabled(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_4.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget_Email1)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_4.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.widget_Email1)
        self.radioButton_6.setEnabled(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_4.addWidget(self.radioButton_6)
        self.gridLayout_2.addWidget(self.widget_Email1, 4, 0, 1, 1)
        self.widget_Email = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_Email.setObjectName("widget_Email")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_Email)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_Email)
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.label_ = QtWidgets.QLabel(self.widget_Email)
        self.label_.setObjectName("label_")
        self.horizontalLayout_3.addWidget(self.label_)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_Email)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.gridLayout_2.addWidget(self.widget_Email, 3, 0, 1, 1)
        self.widget_Password1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_Password1.setObjectName("widget_Password1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_Password1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_7 = QtWidgets.QWidget(self.widget_Password1)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_6.addWidget(self.lineEdit_4)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget_7)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_6.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget_7)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_6.addWidget(self.checkBox_5)
        self.spinBox = QtWidgets.QSpinBox(self.widget_7)
        self.spinBox.setMinimum(0)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.verticalLayout.addWidget(self.widget_7)
        self.Generat_Password_2 = QtWidgets.QPushButton(self.widget_Password1)
        self.Generat_Password_2.setObjectName("Generat_Password_2")
        self.verticalLayout.addWidget(self.Generat_Password_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.widget_Password1, 6, 0, 1, 1)
        self.widget_Edit = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_Edit.setObjectName("widget_Edit")
        self.gridLayout_2.addWidget(self.widget_Edit, 7, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.checkBox_password.toggled['bool'].connect(self.widget_Password1.setVisible) # type: ignore
        self.checkBox_2.toggled['bool'].connect(self.widget_Email1.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Name"))
        self.label.setText(_translate("Form", "OR"))
        self.checkBox.setText(_translate("Form", "Random"))
        self.lineEdit_password.setPlaceholderText(_translate("Form", "Password"))
        self.label_5.setText(_translate("Form", "OR"))
        self.checkBox_password.setText(_translate("Form", "Random"))
        self.label_3.setText(_translate("Form", "Gender:"))
        self.radioButton.setText(_translate("Form", "Male"))
        self.radioButton_2.setText(_translate("Form", "Femal"))
        self.radioButton_3.setText(_translate("Form", "Random"))
        self.radioButton_4.setText(_translate("Form", "Moakt"))
        self.radioButton_5.setText(_translate("Form", "Mail-Tm"))
        self.radioButton_6.setText(_translate("Form", "Random"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Email"))
        self.label_.setText(_translate("Form", "OR"))
        self.checkBox_2.setText(_translate("Form", "Random"))
        self.lineEdit_4.setText(_translate("Form", "010"))
        self.checkBox_4.setText(_translate("Form", "Number"))
        self.checkBox_5.setText(_translate("Form", "Letters"))
        self.Generat_Password_2.setText(_translate("Form", "Generat Password"))
